name: Docs & Changelog

on:
  push:
    branches:
      - main

jobs:
  call-tf-docs-workflow:
    uses: rafalkrol-xyz/github-actions-workflows/.github/workflows/terraform_docs.yml@v1.2.0
  call-changelog-workflow:
    uses: rafalkrol-xyz/github-actions-workflows/.github/workflows/changelog.yml@v1.2.0
    needs: call-tf-docs-workflow
